apiVersion: v1
kind: Service
metadata:
  name: simple-node-js-service
spec:
  type: NodePort
  selector:
    app: simple-node-js-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007

